Resolving the text overflow in Divs ( "What comes after implementation" and "About" section)
creativecommons/mp pull request #78
Opened 2021-02-13 06:47 UTC by renuka142

## Fixes
fixes #76 by @shubhanshu02
## Description
The PR resolves the text overflow occuring in the Div section i.e
 - What comes after implementation
 - About
 
When viewed on devices with a width between 768px to around 1300px.
## Technical Details
changed some hardcoded widths and heights from these cards , for the pt-card and pt-text-card classes:

## Tests
1) Open the "ABOUT" section of the page.
2) Adjust the width size between 768px to 1300px.
3) Notice that the text overflow which was occuring previously is rectified.
4) Follow step 1 and 2 for "WHAT COMES AFTER IMPLEMENTATION" section.

## Screenshot
![Screenshot (167)](https://user-images.githubusercontent.com/72491412/107843804-0fd50a80-6df4-11eb-819e-dec8f4e5064e.png)

![Screenshot (169)](https://user-images.githubusercontent.com/72491412/107843863-8ffb7000-6df4-11eb-8b63-cc6d9d59043b.png)

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-02-14 08:09 UTC, Cronus1007 requested changes

2021-02-14 08:09 UTC, Cronus1007 commented on docs/index.html
> +          <p class="text-normal">This toolkit brings all the elements for a basic Creative Commons platform integration.</p>
@renuka142 Thanks for your contribution! 
Plzzz revert this unnecessary change of linting. Make it in accordance with the complete repo.

2021-02-14 08:09 UTC, Cronus1007 commented on docs/src/css/style.css
> +
@renuka142 Unnecessary spacing.

2021-02-14 08:09 UTC, Cronus1007 commented on docs/src/css/style.css
> +
@renuka142 Unnecessary spacing.

2021-02-14 08:09 UTC, Cronus1007 commented on docs/src/css/style.css
> +
@renuka142 Unnecessary spacing.

2021-02-14 08:09 UTC, Cronus1007 commented on docs/src/css/style.css
> +
@renuka142 Unnecessary spacing.

2021-02-14 08:09 UTC, Cronus1007 commented on docs/src/css/style.css
> +
@renuka142 Unnecessary spacing.

2021-02-14 08:10 UTC, Cronus1007 commented
@renuka142 The PR seems good. Have a look upon the required changes.

2021-02-14 08:16 UTC, renuka142 commented
Hello @Cronus1007 , sure i will do the above changes.
Thankyou for your remarks!

2021-02-14 09:29 UTC, Cronus1007 commented
@renuka142 Have a look about this ss
![Screenshot from 2021-02-14 14-58-20](https://user-images.githubusercontent.com/56436023/107873023-2bfca880-6ed5-11eb-897f-cbac85c5b0df.png)
.

2021-02-14 09:35 UTC, renuka142 commented
Okay , the two cards needs to be aligned.

2021-10-04 07:43 UTC, brylie approved these changes

2021-10-04 07:45 UTC, merged